spring:
  application:
    name: photo-cloud-server
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mail:
    host: smtp.yandex.ru
    port: 465
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    mail-from: ${SMTP_USERNAME}@yandex.ru

server:
  servlet:
    context-path: /
  port: 8080

token:
  signing:
    key: ${JWT_KEY}

storage:
  baseStoragePath: storage # базовый путь хранения файлов

logging:
  level:
    liquibase: info
