package ru.tbcarus.photocloudserver.exception.dto;

public enum ErrorCode {
    VALIDATION_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    BAD_REQUEST,
    NOT_FOUND,
    CONFLICT,
    INVALID_CREDENTIALS,
    INVALID_REFRESH_TOKEN,
    REFRESH_TOKEN_REVOKED,
    REFRESH_TOKEN_NOT_FOUND,
    REFRESH_TOKEN_OWNERSHIP_ERROR,
    FILE_ITEM_NOT_FOUND,
    BAD_REGISTRATION_REQUEST,
    DATABASE_CONSTRAINT_VIOLATION,
    INTERNAL_ERROR
}
