--liquibase formatted sql

-- changeset author:01-user
CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(128)       NOT NULL,
    email    VARCHAR(128)       NOT NULL,
    password VARCHAR(128)       NOT NULL,
    enabled  bool DEFAULT FALSE NOT NULL,
    banned   bool DEFAULT FALSE NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_uindex ON users (email);


CREATE TABLE user_roles
(
    user_id INTEGER NOT NULL,
    role    VARCHAR(255),
    CONSTRAINT user_roles_idx UNIQUE (user_id, role),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);