--liquibase formatted sql

-- changeset author:01-user
CREATE TABLE IF NOT EXISTS users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(128)       NOT NULL,
    password    VARCHAR(128)       NOT NULL,
    first_name  VARCHAR(128),
    last_name   VARCHAR(128),
    enabled     bool DEFAULT FALSE NOT NULL,
    banned      bool DEFAULT FALSE NOT NULL,
    created_at  TIMESTAMP,
    last_update TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_uindex ON users (email);


CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL,
    role    VARCHAR(255),
    CONSTRAINT user_roles_idx UNIQUE (user_id, role),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);