--liquibase formatted sql

-- changeset author:02-refresh-token
CREATE TABLE IF NOT EXISTS refresh_token
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token      VARCHAR(255) NOT NULL,
    user_name  VARCHAR(255) NOT NULL,
    expires    TIMESTAMP    NOT NULL,
    revoked    BOOLEAN DEFAULT FALSE,
    revoked_at TIMESTAMP
);
CREATE INDEX refresh_token_user ON refresh_token (user_name);